"""
email_notification_service/email_template.py
--------------------------------------------
Generates a professional, medically compliant HTML email body
(with a plain-text fallback) for Medivio follow-ups.

Design rules enforced in code:
  - 12 sections in exact mandated order
  - Emergency override short-circuits ALL other sections
  - Allergy conflicts checked before every medicine and food suggestion
  - OTC / wellness suggestions only - no prescription-only medications
  - No certain diagnoses - qualified language only ("may be", "could indicate")
  - Ends with exact verbatim legal disclaimer

Public API:
    build_consultation_email(patient_data: dict) -> dict
        Returns {
            "subject": str,
            "text_body": str,
            "html_body": str,
            "to_email": str
        }
"""

import logging
from datetime import datetime

logger = logging.getLogger(__name__)

# ── Emergency trigger keywords ────────────────────────────────────────────────
_EMERGENCY_KEYWORDS = (
    "chest pain",
    "difficulty breathing",
    "can't breathe",
    "cannot breathe",
    "shortness of breath",
    "stroke",
    "face drooping",
    "slurred speech",
    "loss of consciousness",
    "fainted",
    "unresponsive",
    "severe bleeding",
    "coughing blood",
    "vomiting blood",
    "seizure",
    "convulsion",
    "suicidal",
    "want to die",
    "kill myself",
    "self-harm",
    "anaphylaxis",
    "severe allergic reaction",
    "throat swelling",
    "swollen throat",
)

# ── Verbatim mandatory legal disclaimer ───────────────────────────────────────
_MEDICAL_DISCLAIMER = (
    "This email was generated by an AI assistant for informational purposes only "
    "and does not constitute medical advice. Please consult a licensed physician "
    "before starting, stopping, or changing any treatment, medication, or diet."
)

_SEP = "-" * 60   # Section divider line for plain text

# ── NOTE: All HTML styles are INLINED directly on elements ────────────────────
# Gmail, Outlook, and Yahoo strip <style> blocks entirely. Using CSS classes
# in emails causes them to render as unstyled plaintext (ugly) and triggers
# spam filters (suspicious). All styles MUST be inline on every element.
# This is the #1 production email deliverability best practice.


# ─────────────────────────────────────────────────────────────────────────────
# Internal helpers
# ─────────────────────────────────────────────────────────────────────────────

def _is_emergency(patient_data: dict) -> bool:
    """
    Return True if any emergency keyword appears in the combined
    symptoms_description, symptom_tags, or ai_assessment fields.
    """
    combined = " ".join([
        str(patient_data.get("symptoms_description", "")),
        str(patient_data.get("symptom_tags", "")),
        str(patient_data.get("ai_assessment", "")),
    ]).lower()

    for kw in _EMERGENCY_KEYWORDS:
        if kw in combined:
            logger.warning(
                "[EmailTemplate] Emergency keyword '%s' detected - switching to emergency email.", kw
            )
            return True
    return False


def _build_emergency_email(patient_name: str) -> dict:
    """
    Return ONLY an urgent short message. All other sections are skipped.
    Required by strict medical rules when emergency keywords are detected.
    """
    subject = "URGENT - Please Seek Emergency Medical Care Immediately"

    # Plain text version
    text_body = "\n".join([
        f"Dear {patient_name},",
        "",
        "Based on the symptoms you described in your recent Medivio consultation,",
        "your condition may require IMMEDIATE emergency medical attention.",
        "",
        "Please do ONE of the following RIGHT NOW:",
        "",
        "  1. Call 112 (National Emergency) or 102 (Ambulance) immediately.",
        "  2. Ask someone to drive you to the nearest emergency room.",
        "  3. Do NOT drive yourself.",
        "",
        "Do NOT wait for further AI advice, home remedies, or medications.",
        "This situation requires in-person emergency care - not AI guidance.",
        "",
        _SEP,
        _MEDICAL_DISCLAIMER,
    ])

    # Colorful HTML version - fully inlined styles (no <style> block)
    html_body = f"""<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Emergency Medical Alert - Medivio</title>
</head>
<body style="margin: 0; padding: 0; font-family: Arial, Helvetica, sans-serif; line-height: 1.6; color: #334155; background-color: #f8fafc; -webkit-font-smoothing: antialiased;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #f8fafc;">
        <tr><td align="center" style="padding: 20px 10px;">
            <table role="presentation" width="680" cellpadding="0" cellspacing="0" style="max-width: 680px; width: 100%; background-color: #ffffff; border-radius: 12px; overflow: hidden; border: 1px solid #e2e8f0;">
                <!-- HEADER -->
                <tr>
                    <td style="background: linear-gradient(135deg, #dc2626, #b91c1c); padding: 30px 24px; text-align: center; color: #ffffff;">
                        <div style="display: inline-block; background-color: rgba(255,255,255,0.2); padding: 10px; border-radius: 50%; margin-bottom: 12px; border: 1px solid rgba(255,255,255,0.25);">
                            <img src="https://img.icons8.com/ios-filled/32/ffffff/plus-math.png" alt="+" width="32" height="32" style="display: block;">
                        </div>
                        <h1 style="margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; color: #ffffff;">EMERGENCY CARE REQUIRED</h1>
                        <p style="margin: 4px 0 0 0; font-size: 14px; color: #fecaca; font-weight: 500;">Immediate Medical Action Advised</p>
                    </td>
                </tr>
                <!-- CONTENT -->
                <tr>
                    <td style="padding: 30px 24px;">
                        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #fef2f2; border: 1px solid #fca5a5; border-left: 4px solid #dc2626; border-radius: 8px; padding: 20px; margin-bottom: 20px;">
                            <tr><td style="padding: 20px;">
                                <h2 style="font-size: 16px; font-weight: 700; color: #991b1b; margin: 0 0 12px 0; text-transform: uppercase; letter-spacing: 0.5px;">&#128680; Action Required Immediately</h2>
                                <p style="font-size: 14px; color: #334155;">Dear <strong>{patient_name}</strong>,</p>
                                <p style="font-size: 14px; color: #334155;">Based on the symptom descriptors you provided, your condition may indicate a critical event requiring <strong>IMMEDIATE emergency care</strong>.</p>
                                <p style="font-size: 14px; color: #334155;"><strong>Please take one of the following steps immediately:</strong></p>
                                <ul style="margin: 0; padding-left: 20px;">
                                    <li style="margin-bottom: 8px; font-size: 14px; color: #334155;"><strong>Call 112</strong> (National Emergency number) or <strong>102</strong> (Ambulance services) right away.</li>
                                    <li style="margin-bottom: 8px; font-size: 14px; color: #334155;">Ask a family member, neighbor, or friend to drive you to the nearest Emergency Department.</li>
                                    <li style="margin-bottom: 8px; font-size: 14px; color: #334155;"><strong>Do not drive yourself</strong> to the hospital.</li>
                                </ul>
                                <p style="margin-top: 15px; font-weight: bold; color: #dc2626; font-size: 14px;">Do NOT wait for further AI advice, OTC medicines, or home remedies.</p>
                            </td></tr>
                        </table>
                        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 18px; margin-top: 30px;">
                            <tr><td style="padding: 18px; text-align: center;">
                                <div style="font-weight: 700; color: #475569; margin-bottom: 6px; text-transform: uppercase; font-size: 12px;">Medical Disclaimer</div>
                                <p style="font-size: 12px; color: #64748b; line-height: 1.5; margin: 0;">{_MEDICAL_DISCLAIMER}</p>
                            </td></tr>
                        </table>
                    </td>
                </tr>
                <!-- FOOTER -->
                <tr>
                    <td style="padding: 24px; background-color: #f1f5f9; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0;">
                        Warm regards,<br>
                        <strong>Medivio Team</strong><br>
                        Automated Patient Alerts - Do not reply
                    </td>
                </tr>
            </table>
        </td></tr>
    </table>
</body>
</html>
"""

    return {
        "subject":   subject,
        "text_body": text_body,
        "html_body": html_body,
    }


def _has_allergy_conflict(item_name: str, allergies_text: str) -> bool:
    """Case-insensitive substring check: return True if item appears in allergies."""
    if not allergies_text:
        return False
    return item_name.lower() in allergies_text.lower()


# ─────────────────────────────────────────────────────────────────────────────
# Core Section HTML & Text Builders
# ─────────────────────────────────────────────────────────────────────────────

def _build_condition_summary(ai_assessment: str, symptoms: str) -> tuple:
    """
    Condition Summary section.
    Returns: (plain_text_str, html_str)
    """
    clean = (
        str(ai_assessment)
        .replace("**", "").replace("*", "").replace("#", "").replace("`", "")
        .strip()
    )

    body_text = clean if clean else (
        "This may be related to the symptoms you reported. "
        "A thorough in-person examination is needed to determine the cause."
    )

    # 1. Plain Text
    text = "\n".join([
        f"\n{_SEP}\nCONDITION SUMMARY\n{_SEP}",
        "",
        "Based on what you have described, this could indicate the following:",
        "",
        body_text,
        "",
        "Please note: This is not a confirmed diagnosis. Only a licensed physician",
        "can diagnose a medical condition after a proper clinical examination.",
    ])

    # 2. HTML
    html = f"""
    <div style="margin-bottom:24px;padding:20px;background-color:#ffffff;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;">
        <h2 style="margin:0 0 14px 0;font-size:17px;font-weight:700;color:#0f766e;letter-spacing:-0.3px;">🩺 Condition Summary</h2>
        <p>Based on the symptoms you reported, this may indicate the following:</p>
        <p style="background-color: #f8fafc; padding: 15px; border-radius: 6px; border: 1px solid #e2e8f0; font-style: italic; color: #1e293b;">
            "{body_text}"
        </p>
        <p style="font-size: 13px; color: #64748b; margin-top: 12px; line-height: 1.4;">
            <strong>Please note:</strong> This is an initial AI intake analysis and is not a confirmed medical diagnosis. A clinical assessment by a licensed provider is required to determine your diagnosis.
        </p>
    </div>
    """

    return text, html


def _build_medicine_section(ai_assessment: str, medical_history: str, allergies: str) -> tuple:
    """
    Medicine Suggestions section.
    - OTC / wellness only
    - Dosage line defers to doctor/pharmacist
    - Allergy conflict checks
    Returns: (plain_text_str, html_str)
    """
    # Plain text setup
    text_lines = [
        f"\n{_SEP}\nMEDICINE SUGGESTIONS\n{_SEP}",
        "",
        "The following are general over-the-counter (OTC) wellness suggestions",
        "that may provide relief. These are NOT prescriptions.",
        "",
        "IMPORTANT: Confirm all medicines with your doctor or pharmacist before",
        "taking them, especially if you have existing health conditions.",
        "",
    ]

    # HTML setup
    html_header = """
    <div style="margin-bottom:24px;padding:20px;background-color:#ffffff;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;">
        <h2 style="margin:0 0 14px 0;font-size:17px;font-weight:700;color:#0f766e;letter-spacing:-0.3px;">💊 Medicine Suggestions (OTC Only)</h2>
        <p style="font-size: 13px; color: #64748b; margin-bottom: 15px;">
            The following list highlights common over-the-counter (OTC) support products related to your described symptoms. <strong>These are NOT prescriptions.</strong> Verify all choices with a doctor or pharmacist.
        </p>
    """
    html_items = []

    # OTC map: (symptom keyword, medicine suggestion, allergy-safe alternative)
    otc_map = [
        ("fever",       "Paracetamol (e.g. Dolo 650 or Crocin 650)",               "Ibuprofen (after meals, if no stomach issues)"),
        ("pain",        "Paracetamol (e.g. Dolo 650)",                             "Topical diclofenac gel for localised pain"),
        ("headache",    "Paracetamol (e.g. Dolo 650)",                             "Cold compress on forehead"),
        ("cold",        "Strepsils lozenges for throat soothing",                  "Honey and warm water gargle"),
        ("cough",       "ORS (Electral) to stay hydrated during cough",            "Warm turmeric milk"),
        ("sore throat", "Strepsils lozenges",                                      "Warm salt-water gargle"),
        ("acidity",     "Antacid such as Digene or Gelusil MPS (chewed after meals)", "Plain cold milk in small sips"),
        ("indigestion", "Pudin Hara capsules (after meals)",                       "Ajwain (carom seeds) with warm water"),
        ("nausea",      "ORS (Electral) to replace lost fluids",                   "Ginger tea in small sips"),
        ("diarrhea",    "ORS (Electral) - one sachet dissolved in 1 litre of water", "Coconut water for hydration"),
        ("allergic",    "Cetirizine 10mg (e.g. Cetzine) - non-drowsy option: Fexofenadine (Allegra 120)", "Consult your doctor if allergy is severe"),
        ("congestion",  "Saline nasal drops (available without prescription)",     "Steam inhalation with hot water"),
        ("muscle",      "Topical pain relief gel (e.g. Moov or Volini spray)",     "Warm compress on the affected area"),
    ]

    combined_text = f"{ai_assessment} {medical_history}".lower()
    found_any = False

    for keyword, medicine, alternative in otc_map:
        if keyword in combined_text:
            found_any = True
            base_name = medicine.split("(")[0].strip()
            
            # Check for allergy conflict
            is_allergic = _has_allergy_conflict(base_name, allergies) or _has_allergy_conflict(keyword, allergies)
            
            if is_allergic:
                # Text
                text_lines.append(
                    f"  Note: {medicine} was considered for your {keyword} symptoms but\n"
                    f"  may conflict with your recorded allergies.\n"
                    f"  Allergy-safe alternative: {alternative}\n"
                )
                # HTML
                html_items.append(f"""
                <div style="margin-bottom:10px;padding:12px;border:1px solid #e2e8f0;border-left:3px solid #eab308;border-radius:6px;background-color:#fffbeb;">
                    <div style="font-weight:700;font-size:14px;color:#1e293b;" style="color: #854d0e;">⚠️ Allergy Conflict Detected</div>
                    <div style="font-size:13px;color:#64748b;margin-top:4px;" style="margin-top: 4px; color: #a16207;">
                        "{medicine}" was flagged as matching your allergy profile.
                    </div>
                    <div style="font-size:13px;color:#dc2626;margin-top:6px;font-weight:600;">Suggested Allergy-Safe Option: {alternative}</div>
                </div>
                """)
            else:
                # Text
                text_lines.append(f"  {medicine}")
                text_lines.append("  (Dosage: Please confirm with your doctor or pharmacist)\n")
                
                # HTML
                html_items.append(f"""
                <div style="margin-bottom:10px;padding:12px;border:1px solid #e2e8f0;border-left:3px solid #0d9488;border-radius:6px;background-color:#f8fafc;">
                    <div style="font-weight:700;font-size:14px;color:#1e293b;">🔹 {medicine}</div>
                    <div style="font-size:13px;color:#64748b;margin-top:4px;">Dosage: As recommended by doctor/pharmacist. Do not exceed suggested packaging instructions.</div>
                </div>
                """)

    if not found_any:
        text_lines.append(
            "  No specific OTC suggestions matched your symptom description.\n"
            "  Please consult your pharmacist or doctor for personalised guidance."
        )
        html_items.append("""
        <p style="font-style: italic; color: #64748b; font-size: 14px;">
            No specific OTC suggestions matched your symptom description. Please consult a professional.
        </p>
        """)

    text = "\n".join(text_lines)
    html = html_header + "\n".join(html_items) + "\n</div>"
    
    return text, html


def _build_diet_plan(allergies: str) -> tuple:
    """
    Diet Plan section.
    Returns: (plain_text_str, html_str)
    """
    text_lines = [
        f"\n{_SEP}\nDIET PLAN\n{_SEP}",
        "",
        "A balanced, easy-to-digest diet supports recovery. General suggestions:",
        "",
    ]

    html_header = """
    <div style="margin-bottom:24px;padding:20px;background-color:#ffffff;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;">
        <h2 style="margin:0 0 14px 0;font-size:17px;font-weight:700;color:#0f766e;letter-spacing:-0.3px;">🥗 Diet Plan</h2>
        <p style="font-size: 13px; color: #64748b; margin-bottom: 12px;">Suggested nutrition guidelines for recovery:</p>
        <ul style="padding-left:20px;margin:0 0 15px 0;line-height:1.8;font-size:14px;color:#334155;">
    """
    html_items = []

    suggestions = [
        ("Khichdi",                          "Plain boiled rice with vegetables"),
        ("Fresh fruits",                     "Pomegranate or guava if citrus causes issues"),
        ("Steamed or boiled vegetables",     "Salads with light dressing"),
        ("Yoghurt",                          "Coconut milk-based dishes if dairy is an issue"),
        ("Warm soups and broths",            "Clear vegetable broth"),
        ("Green tea or ginger tea",          "Plain warm water with lemon"),
    ]

    for food, alternative in suggestions:
        if _has_allergy_conflict(food, allergies):
            text_lines.append(f"  Allergy-safe alternative: {alternative}")
            html_items.append(f'<li style="color: #b45309;">⚠️ <strong>Allergy-safe alternative:</strong> {alternative}</li>')
        else:
            text_lines.append(f"  {food}")
            html_items.append(f'<li>{food}</li>')

    text_lines += [
        "",
        "  Foods to limit during this period:",
        "  - Spicy, oily, or heavily processed foods",
        "  - Alcohol and caffeinated drinks (coffee, energy drinks)",
        "  - Raw or unwashed fruits and vegetables",
        "  - High-sugar snacks and sodas",
    ]

    html_limit_section = """
        </ul>
        <p style="font-size: 14px; font-weight: 700; color: #475569; margin: 15px 0 6px 0;">🚫 Foods to Limit:</p>
        <ul style="padding-left:20px;margin:0;line-height:1.8;font-size:14px;color:#64748b;">
            <li>Spicy, deep-fried, or oily meals</li>
            <li>Alcohol, coffee, and energy drinks</li>
            <li>Raw/unwashed produce (ensure everything is fully cooked)</li>
            <li>High-sugar snacks, sweets, and sodas</li>
        </ul>
    </div>
    """

    text = "\n".join(text_lines)
    html = html_header + "\n".join(html_items) + html_limit_section
    return text, html


def _build_daily_routine() -> tuple:
    """
    Daily Routine section.
    Returns: (plain_text_str, html_str)
    """
    text = "\n".join([
        f"\n{_SEP}\nDAILY ROUTINE\n{_SEP}",
        "",
        "A consistent daily routine supports your body's natural healing process:",
        "",
        "  Morning:",
        "  - Wake up at a consistent time (ideally before 7:00 AM)",
        "  - Drink a glass of warm water before breakfast",
        "  - Take any medicines after a light meal unless directed otherwise",
        "",
        "  Afternoon:",
        "  - Eat a light, nutritious lunch",
        "  - Avoid lying down immediately after eating (wait at least 30 minutes)",
        "  - Take a short rest if you feel fatigued",
        "",
        "  Evening:",
        "  - Gentle walk for 15-20 minutes if your condition permits",
        "  - Light dinner at least 2 hours before bedtime",
        "",
        "  Night:",
        "  - Follow the sleep recommendations below",
        "  - Avoid screen time (phone, TV) for 30 minutes before bed",
    ])

    html = """
    <div style="margin-bottom:24px;padding:20px;background-color:#ffffff;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;">
        <h2 style="margin:0 0 14px 0;font-size:17px;font-weight:700;color:#0f766e;letter-spacing:-0.3px;">⏰ Daily Routine</h2>
        <table style="width: 100%; border-collapse: collapse; font-size: 14px; margin-top: 10px;">
            <tr style="border-bottom: 1px solid #f1f5f9;">
                <td style="padding: 10px 0; font-weight: 700; color: #475569; width: 100px; vertical-align: top;">🌅 Morning</td>
                <td style="padding: 10px 0; color: #334155;">
                    Wake up by 7:00 AM. Drink a glass of warm water before breakfast. Take medications after your morning meal unless directed otherwise.
                </td>
            </tr>
            <tr style="border-bottom: 1px solid #f1f5f9;">
                <td style="padding: 10px 0; font-weight: 700; color: #475569; vertical-align: top;">☀️ Afternoon</td>
                <td style="padding: 10px 0; color: #334155;">
                    Eat a light, warm lunch. Do not lie down immediately after eating (remain upright or walk gently for 30 minutes).
                </td>
            </tr>
            <tr style="border-bottom: 1px solid #f1f5f9;">
                <td style="padding: 10px 0; font-weight: 700; color: #475569; vertical-align: top;">🌇 Evening</td>
                <td style="padding: 10px 0; color: #334155;">
                    Gently walk for 15-20 minutes to aid circulation. Consume a light dinner at least 2 hours before sleep.
                </td>
            </tr>
            <tr>
                <td style="padding: 10px 0; font-weight: 700; color: #475569; vertical-align: top;">🌙 Night</td>
                <td style="padding: 10px 0; color: #334155;">
                    Turn off electronic screens (mobile, television) at least 30 minutes before sleep to support natural melatonin levels.
                </td>
            </tr>
        </table>
    </div>
    """
    return text, html


def _build_exercise_section(ai_assessment: str) -> tuple:
    """
    Exercise Recommendations.
    Returns: (plain_text_str, html_str)
    """
    text_lower = ai_assessment.lower()

    if any(w in text_lower for w in ("fever", "severe", "weakness", "fatigue", "exhaustion")):
        level = "Rest"
        text_advice = [
            "  Your body needs rest more than exercise at this stage.",
            "  Avoid strenuous physical activity until your symptoms fully resolve.",
            "  Gentle in-bed stretching or short slow walks around the room are acceptable.",
            "  Resume regular exercise only after getting clearance from your doctor.",
        ]
        html_advice = """
        <p><strong>Recommended activity level: <span style="display:inline-block;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600;background-color:#fee2e2;color:#991b1b;">Rest Required</span></strong></p>
        <ul style="padding-left:20px;margin:10px 0 0 0;line-height:1.8;font-size:14px;color:#64748b;">
            <li>Your body needs rest more than active exercise to rebuild defenses.</li>
            <li>Avoid heavy workouts, cardiovascular exercise, or lifting.</li>
            <li>Acceptable: light static stretches in bed or extremely short slow room walks.</li>
        </ul>
        """
    elif any(w in text_lower for w in ("mild", "slight", "minor")):
        level = "Light Activity"
        text_advice = [
            "  Light exercise is appropriate for your current condition:",
            "  - Walking: 15-20 minutes at a comfortable pace",
            "  - Gentle yoga or stretching: 10-15 minutes",
            "  - Breathing exercises (Pranayama): 5-10 minutes",
            "  Stop immediately if you feel dizzy, short of breath, or in pain.",
        ]
        html_advice = """
        <p><strong>Recommended activity level: <span style="display:inline-block;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600;background-color:#fef3c7;color:#92400e;">Light Activity</span></strong></p>
        <ul style="padding-left:20px;margin:10px 0 0 0;line-height:1.8;font-size:14px;color:#64748b;">
            <li>Gentle walking: 15-20 minutes at an easy, conversational pace.</li>
            <li>Low-impact stretching or gentle yoga: 10-15 minutes.</li>
            <li>Diaphragmatic breathing / Pranayama: 5-10 minutes to support lungs.</li>
            <li style="color: #dc2626; font-weight: 600;">Stop immediately if you experience dizziness, headache, or shortness of breath.</li>
        </ul>
        """
    else:
        level = "Moderate Activity"
        text_advice = [
            "  Moderate, low-impact exercise may be beneficial:",
            "  - Brisk walking: 20-30 minutes daily",
            "  - Gentle yoga or light stretching",
            "  - Avoid high-intensity workouts until symptoms fully resolve",
            "  Always warm up before and cool down after exercise.",
        ]
        html_advice = """
        <p><strong>Recommended activity level: <span style="display:inline-block;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600;background-color:#fee2e2;color:#991b1b;" style="background-color: #dbeafe; color: #1e40af;">Moderate Activity</span></strong></p>
        <ul style="padding-left:20px;margin:10px 0 0 0;line-height:1.8;font-size:14px;color:#64748b;">
            <li>Brisk walking: 20-30 minutes daily is suitable.</li>
            <li>Yoga, Pilates, or bodyweight stretches.</li>
            <li>Avoid heavy weights or high-intensity interval training (HIIT).</li>
        </ul>
        """

    text = "\n".join([
        f"\n{_SEP}\nEXERCISE RECOMMENDATIONS\n{_SEP}",
        "",
        f"Recommended activity level: {level}",
        "",
    ] + text_advice)

    html = f"""
    <div style="margin-bottom:24px;padding:20px;background-color:#ffffff;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;">
        <h2 style="margin:0 0 14px 0;font-size:17px;font-weight:700;color:#0f766e;letter-spacing:-0.3px;">🏃 Exercise Recommendations</h2>
        {html_advice}
    </div>
    """
    return text, html


def _build_hydration_section() -> tuple:
    """
    Hydration Recommendations section.
    Returns: (plain_text_str, html_str)
    """
    text = "\n".join([
        f"\n{_SEP}\nHYDRATION RECOMMENDATIONS\n{_SEP}",
        "",
        "Staying well-hydrated is essential for recovery and overall health:",
        "",
        "  - Aim for 8-10 glasses (2 to 2.5 litres) of clean water per day",
        "  - Increase intake if you have fever, vomiting, or diarrhea",
        "  - Coconut water and ORS (Oral Rehydration Salts) replace lost electrolytes",
        "  - Warm water with honey and lemon can soothe throat irritation",
        "  - Avoid sugary sodas, energy drinks, and excessive caffeine",
        "  - Sip water steadily throughout the day rather than in large amounts",
    ])

    html = """
    <div style="margin-bottom:24px;padding:20px;background-color:#ffffff;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;">
        <h2 style="margin:0 0 14px 0;font-size:17px;font-weight:700;color:#0f766e;letter-spacing:-0.3px;">💧 Hydration Guidance</h2>
        <ul style="padding-left:20px;margin:0;line-height:1.8;font-size:14px;color:#334155;">
            <li><strong>Daily Intake:</strong> Aim for 8 to 10 glasses (approximately 2 to 2.5 liters) of clean water.</li>
            <li><strong>Electrolytes:</strong> If dealing with fever or vomiting, substitute 1-2 glasses with coconut water or ORS (Oral Rehydration Salts).</li>
            <li><strong>Soothe:</strong> Sip warm water with fresh lemon juice and honey to help ease upper respiratory tract dryness.</li>
            <li style="color: #64748b;">Avoid: high-sugar carbonated beverages, energy drinks, and excessive espresso or tea.</li>
        </ul>
    </div>
    """
    return text, html


def _build_sleep_section() -> tuple:
    """
    Sleep Recommendations section.
    Returns: (plain_text_str, html_str)
    """
    text = "\n".join([
        f"\n{_SEP}\nSLEEP RECOMMENDATIONS\n{_SEP}",
        "",
        "Quality sleep is one of the most powerful recovery tools available:",
        "",
        "  - Aim for 7-9 hours of uninterrupted sleep per night",
        "  - Keep your bedroom cool, dark, and quiet",
        "  - Maintain a consistent sleep and wake time, even on weekends",
        "  - Avoid screens (phone, TV, laptop) for at least 30 minutes before bed",
        "  - A warm shower before bed can relax muscles and aid sleep onset",
        "  - Elevate your head slightly if you have nasal congestion or a cough",
        "  - Avoid heavy meals or caffeine within 3 hours of bedtime",
    ])

    html = """
    <div style="margin-bottom:24px;padding:20px;background-color:#ffffff;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;">
        <h2 style="margin:0 0 14px 0;font-size:17px;font-weight:700;color:#0f766e;letter-spacing:-0.3px;">💤 Sleep Recommendations</h2>
        <ul style="padding-left:20px;margin:0;line-height:1.8;font-size:14px;color:#334155;">
            <li><strong>Duration:</strong> Target 7 to 9 hours of continuous sleep to maximize natural recovery cycles.</li>
            <li><strong>Environment:</strong> Keep the bedroom cool, dark, and clear of ambient noises.</li>
            <li><strong>Positioning:</strong> If congested or coughing, elevate your head slightly using an extra pillow.</li>
            <li style="color: #64748b;">Avoid: eating large meals, drinking coffee, or using mobile devices within 3 hours of sleeping.</li>
        </ul>
    </div>
    """
    return text, html


def _build_things_to_avoid(allergies: str) -> tuple:
    """
    Things to Avoid section.
    Returns: (plain_text_str, html_str)
    """
    text_lines = [
        f"\n{_SEP}\nTHINGS TO AVOID\n{_SEP}",
        "",
        "To support your recovery and prevent worsening symptoms, please avoid:",
        "",
        "  - Self-medicating with prescription-only drugs",
        "  - Ignoring worsening symptoms - seek medical attention promptly",
        "  - Sharing food, utensils, or personal items while unwell",
        "  - Smoking or exposure to second-hand smoke",
        "  - Alcohol while unwell or on any medication",
        "  - Prolonged exposure to cold or heavily air-conditioned environments",
        "  - Skipping meals or fasting without medical guidance",
        "",
    ]

    html_header = """
    <div style="margin-bottom:24px;padding:20px;background-color:#ffffff;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;" style="border-left-color: #64748b;">
        <h2 style="margin:0 0 14px 0;font-size:17px;font-weight:700;color:#0f766e;letter-spacing:-0.3px;" style="color: #475569;">⚠️ Things to Avoid</h2>
        <ul style="padding-left:20px;margin:0;line-height:1.8;font-size:14px;color:#334155;">
            <li><strong>Self-medicating</strong> with prescription-only drugs (antibiotics, steroids) without explicit doctor advice.</li>
            <li>Ignoring signs of deterioration (refer to the Follow-up section below).</li>
            <li>Smoking or using tobacco; avoid environments with secondary smoke.</li>
            <li>Consuming alcohol while recovering or taking medications.</li>
    """
    html_items = []

    if allergies and allergies.strip():
        text_lines += [
            "  Based on your recorded allergies, also avoid:",
            f"  - {allergies.strip()}",
            "  - Always read product labels carefully to check for hidden allergens",
            "",
        ]
        html_items.append(f"""
        </ul>
        <div style="margin-top: 15px; padding: 12px; background-color: #fffbeb; border: 1px solid #fef08a; border-radius: 6px; color: #854d0e; font-size: 13px;">
            <strong>Allergy Warnings:</strong> Avoid all products containing <strong>{allergies.strip()}</strong>. Always read label ingredients.
        </div>
        """)
    else:
        html_items.append("</ul>")

    text = "\n".join(text_lines)
    html = html_header + "\n".join(html_items) + "\n</div>"
    return text, html


def _build_followup_section(patient_name: str) -> tuple:
    """
    Follow-up Advice section with clear escalation triggers.
    Returns: (plain_text_str, html_str)
    """
    text = "\n".join([
        f"\n{_SEP}\nFOLLOW-UP ADVICE\n{_SEP}",
        "",
        f"Dear {patient_name}, please seek professional medical attention if:",
        "",
        "  See a doctor SOON if:",
        "  - Symptoms do not improve within 2-3 days",
        "  - Fever stays above 38.5 degrees Celsius for more than 2 days",
        "  - You develop any new or worsening symptoms",
        "  - You develop difficulty swallowing, breathing, or significant pain",
        "",
        "  See a doctor URGENTLY if:",
        "  - You feel severe chest pain, pressure, or tightness",
        "  - You have difficulty breathing even at rest",
        "  - You feel confused, disoriented, or extremely weak",
        "  - You cannot keep fluids down due to persistent vomiting",
        "",
        "  If you believe this is an emergency, call 112 or 102 immediately.",
        "  Do NOT wait for an AI assessment in an emergency.",
    ])

    html = f"""
    <div style="margin-bottom:24px;padding:20px;background-color:#ffffff;border:1px solid #e2e8f0;border-left:4px solid #0d9488;border-radius:8px;" style="border-left-color: #0f766e;">
        <h2 style="margin:0 0 14px 0;font-size:17px;font-weight:700;color:#0f766e;letter-spacing:-0.3px;">📋 Follow-up Escalation Guidelines</h2>
        <p>Dear <strong>{patient_name}</strong>, monitor your condition closely. Seek professional medical evaluation under the following parameters:</p>
        
        <table style="width: 100%; font-size: 13.5px; border-collapse: collapse; margin-top: 10px;">
            <tr style="background-color: #f8fafc; border-bottom: 1px solid #e2e8f0;">
                <td style="padding: 8px; font-weight: 700; color: #854d0e; width: 120px; vertical-align: top;">📆 Schedule Doctor Visit</td>
                <td style="padding: 8px; color: #334155;">
                    If symptoms do not begin to ease after 2-3 days, or if fever remains elevated above 38.5°C (101.3°F) for over 48 hours.
                </td>
            </tr>
            <tr style="background-color: #fef2f2;">
                <td style="padding: 8px; font-weight: 700; color: #991b1b; vertical-align: top;">🚨 Seek Urgent Care</td>
                <td style="padding: 8px; color: #334155;">
                    If you experience chest tightness, respiratory strain, severe lethargy, confusion, or inability to retain fluids.
                </td>
            </tr>
        </table>
        
        <div style="margin-top: 15px; padding: 12px; background-color: #fee2e2; border-radius: 6px; border: 1px solid #fca5a5; font-size: 13px; color: #991b1b; font-weight: 600; text-align: center;">
            ⚠️ In an emergency, bypass AI summaries. Dial 112 or 102 immediately.
        </div>
    </div>
    """
    return text, html


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def build_consultation_email(patient_data: dict) -> dict:
    """
    Assemble the full consultation summary email for a patient.

    Args:
        patient_data (dict): Keys expected:
            patient_name        (str)
            age                 (str | int)
            gender              (str)
            symptoms_description (str)
            symptom_tags        (str | list)
            medical_history     (str)
            allergies           (str)
            ai_assessment       (str)
            user_email          (str)

    Returns:
        dict: {
            "subject": str,
            "text_body": str,
            "html_body": str,
            "to_email": str
        }
    """
    # ── Extract and sanitise ──────────────────────────────────────────────────
    patient_name    = str(patient_data.get("patient_name",          "Patient")).strip() or "Patient"
    age             = str(patient_data.get("age",                   "Not specified"))
    gender          = str(patient_data.get("gender",                "Not specified")).strip()
    symptoms        = str(patient_data.get("symptoms_description",  "")).strip()
    medical_history = str(patient_data.get("medical_history",       "")).strip()
    allergies       = str(patient_data.get("allergies",             "")).strip()
    ai_assessment   = str(patient_data.get("ai_assessment",         "")).strip()
    user_email      = str(patient_data.get("user_email",            "")).strip()

    # ── EMERGENCY OVERRIDE ────────────────────────────────────────────────────
    if _is_emergency(patient_data):
        result = _build_emergency_email(patient_name)
        result["to_email"] = user_email
        return result

    # ── Normal consultation email ─────────────────────────────────────────────
    now     = datetime.now().strftime("%d %B %Y at %I:%M %p")
    subject = f"Your Medivio Consultation Summary - {now}"

    # We build both Plain Text (fallback) and HTML lists
    text_sections = []
    html_sections = []

    # ── 1. Greeting ───────────────────────────────────────────────────────────
    # Text
    text_sections.append("\n".join([
        f"Dear {patient_name},",
        "",
        "Thank you for using the Medivio service.",
        f"This email is your follow-up summary based on the information you submitted on {now}.",
        "",
        "Patient details on file:",
        f"  Name   : {patient_name}",
        f"  Age    : {age}",
        f"  Gender : {gender}",
        "",
        "Please read this summary carefully and consult a licensed healthcare",
        "professional before taking any action.",
    ]))

    # HTML - ALL styles must be inline (Gmail/Outlook/Yahoo strip <style> blocks)
    html_greeting = f"""
    <div style="margin-bottom: 24px; padding: 20px; background-color: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px;">
        <h3 style="margin: 0 0 10px 0; font-size: 18px; color: #1e293b;">Dear <strong>{patient_name}</strong>,</h3>
        <p style="margin: 0 0 15px 0; font-size: 14.5px; color: #475569;">
            Thank you for completing your digital case intake. Below is the advisory protocol validated by our Medical Consultation Board.
        </p>
        <ul style="list-style: none; padding: 0; margin: 0;">
            <li style="padding: 6px 0; font-size: 14px; color: #334155; border-bottom: 1px solid #e2e8f0;"><strong>Patient Name:</strong> {patient_name}</li>
            <li style="padding: 6px 0; font-size: 14px; color: #334155; border-bottom: 1px solid #e2e8f0;"><strong>Age / Gender:</strong> {age} / {gender}</li>
            <li style="padding: 6px 0; font-size: 14px; color: #334155;"><strong>Logged At:</strong> {now}</li>
        </ul>
    </div>
    """
    html_sections.append(html_greeting)

    # ── 2. Condition Summary ──────────────────────────────────────────────────
    t_sec, h_sec = _build_condition_summary(ai_assessment, symptoms)
    text_sections.append(t_sec)
    html_sections.append(h_sec)

    # ── 3. Medicine Suggestions ──────────────────────────────────────────────
    t_sec, h_sec = _build_medicine_section(ai_assessment, medical_history, allergies)
    text_sections.append(t_sec)
    html_sections.append(h_sec)

    # ── 4. Diet Plan ──────────────────────────────────────────────────────────
    t_sec, h_sec = _build_diet_plan(allergies)
    text_sections.append(t_sec)
    html_sections.append(h_sec)

    # ── 5. Daily Routine ──────────────────────────────────────────────────────
    t_sec, h_sec = _build_daily_routine()
    text_sections.append(t_sec)
    html_sections.append(h_sec)

    # ── 6. Exercise Recommendations ───────────────────────────────────────────
    t_sec, h_sec = _build_exercise_section(ai_assessment)
    text_sections.append(t_sec)
    html_sections.append(h_sec)

    # ── 7. Hydration Recommendations ──────────────────────────────────────────
    t_sec, h_sec = _build_hydration_section()
    text_sections.append(t_sec)
    html_sections.append(h_sec)

    # ── 8. Sleep Recommendations ──────────────────────────────────────────────
    t_sec, h_sec = _build_sleep_section()
    text_sections.append(t_sec)
    html_sections.append(h_sec)

    # ── 9. Things to Avoid ────────────────────────────────────────────────────
    t_sec, h_sec = _build_things_to_avoid(allergies)
    text_sections.append(t_sec)
    html_sections.append(h_sec)

    # ── 10. Follow-up Advice ──────────────────────────────────────────────────
    t_sec, h_sec = _build_followup_section(patient_name)
    text_sections.append(t_sec)
    html_sections.append(h_sec)

    # ── 11. Medical Disclaimer (verbatim) ─────────────────────────────────────
    # Text
    text_sections.append("\n".join([
        f"\n{_SEP}",
        "MEDICAL DISCLAIMER",
        _SEP,
        "",
        _MEDICAL_DISCLAIMER,
    ]))
    
    # HTML
    html_disclaimer = f"""
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; margin-top: 30px;">
        <tr><td style="padding: 18px; text-align: center;">
            <div style="font-weight: 700; color: #475569; margin-bottom: 6px; text-transform: uppercase; font-size: 12px;">Medical Disclaimer</div>
            <p style="font-size: 12px; color: #64748b; line-height: 1.5; margin: 0;">{_MEDICAL_DISCLAIMER}</p>
        </td></tr>
    </table>
    """
    html_sections.append(html_disclaimer)

    # ── 12. Sign-off ──────────────────────────────────────────────────────────
    # Text
    text_sections.append("\n".join([
        "",
        "Warm regards,",
        "Medivio Team",
        "(Automated System - Please do not reply to this email)",
    ]))

    # Combine Plain Text
    full_text_body = "\n".join(text_sections)

    # Combine HTML Body - FULLY INLINE (no <style> block, no CSS classes, no SVG)
    # Gmail/Outlook/Yahoo strip <style> blocks. Table layout for Outlook Word renderer.
    full_html_body = f"""<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Medivio Consultation Summary</title>
</head>
<body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;line-height:1.6;color:#334155;background-color:#f8fafc;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8fafc;">
        <tr><td align="center" style="padding:20px 10px;">
            <table role="presentation" width="680" cellpadding="0" cellspacing="0" style="max-width:680px;width:100%;background-color:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e2e8f0;">
                <tr>
                    <td style="background:linear-gradient(135deg,#0f766e,#0d9488);padding:30px 24px;text-align:center;color:#ffffff;">
                        <div style="display:inline-block;background-color:rgba(255,255,255,0.2);padding:10px 14px;border-radius:50%;margin-bottom:12px;border:1px solid rgba(255,255,255,0.25);">
                            <span style="font-size:28px;font-weight:700;color:#ffffff;">&#43;</span>
                        </div>
                        <h1 style="margin:0;font-size:24px;font-weight:700;letter-spacing:-0.5px;color:#ffffff;">Medivio</h1>
                        <p style="margin:4px 0 0 0;font-size:14px;color:#ccfbf1;font-weight:500;">Case Assessment &amp; Consultation Board</p>
                    </td>
                </tr>
                <tr>
                    <td style="padding:30px 24px;">
                        {"".join(html_sections)}
                    </td>
                </tr>
                <tr>
                    <td style="padding:24px;background-color:#f1f5f9;text-align:center;font-size:12px;color:#64748b;border-top:1px solid #e2e8f0;">
                        Warm regards,<br>
                        <strong>Medivio Team</strong><br>
                        Automated Clinical Report - Please do not reply directly to this mail.
                    </td>
                </tr>
            </table>
        </td></tr>
    </table>
</body>
</html>
"""

    logger.info(
        "[EmailTemplate] HTML and plain text email built for '%s'.", patient_name
    )

    return {
        "subject":   subject,
        "text_body": full_text_body,
        "html_body": full_html_body,
        "to_email":  user_email,
    }
